language: node_js
node_js:
  - lts/*
sudo: required
cache:
  directories:
    - node_modules
before_script:
  - chmod -R +x ./ci/
  - "./ci/version_control"
install:
  - npm install
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/about-me
  on:
    branch: master
    tags: true
